
from .data_set_sick import SickDataset
from .data_set_sts import StsDataset
from .data_set_sts12 import Sts12Dataset
from .data_set_sts13 import Sts13Dataset
from .data_set_sts14 import Sts14Dataset
from .data_set_sts15 import Sts15Dataset
from .data_set_sts16 import Sts16Dataset
from .data_set_custom import CustomDataset
from .data_set_newsela import NewselaDataset
from .data_set_newsela_binary import NewselaBinaryDataset
from .data_set_newsela_document import NewselaDocumentDataset
from .data_set_newsela_test import NewselaTestDataset
from .data_set_test import TestDataset
from .data_set_sts_multi import StsMultiDataset
from .data_set_custom_document import CustomDocumentDataset
from .data_set_newsela_pair_dataset import NewselaPairDataset
from .data_set_capito import CapitoDataset
from .data_set_capito_positive_only import CapitoPositiveDataset
from .data_set_xnli_neutral_only import XNLIDataset
from .data_set_wiki_test import WikiDataset
from .data_set_sick_hetero import SickHeteroDataset
